#!/bin/bash
# FILE:    getversion
# CONTEXT: Run on the host to avoid installing git in the Docker image
# PURPOSE: Generate VERSION file with the current git tag and commit info

set -euo pipefail
git describe --tags | perl -pe 's/(.*)-([0-9]*)-(g[0-9a-f]*)/\1+dev.\2.\3/' > "$(dirname "$0")/VERSION"
