#!/bin/bash
set -e

# Remove the $GPHOME/bin symlinks created by postinst.
for gphome in /opt/greengagedb/greengage*/; do
    [ -d "${gphome}bin" ] || continue
    rm -f "${gphome}bin/gpbackup_s3_plugin"
done

#DEBHELPER#
