name: Build deb

on:
  push:
    branches: ['master']
    tags: ['**']
  pull_request:
    branches: ['**']

jobs:
  build_deb:
    strategy:
      fail-fast: false
      matrix:
        ubuntu_version: ["22.04", "24.04"]
    uses: greengagedb/greengage-ci/.github/workflows/greengage-reusable-deb-native.yml@CI-5788
    with:
      go_version: "1.23"
      artifact_name: "gpbackup-s3-plugin-deb-ubuntu${{ matrix.ubuntu_version }}"
      build_command: "make deb"
      runner: "ubuntu-${{ matrix.ubuntu_version }}"
      test_docker: "ubuntu:${{ matrix.ubuntu_version }}"
      add_greengage_repo: true
      greengage_repo_url: "https://storage.yandexcloud.net/greengage-repo"
      verify_commands: dpkg -l greengage* gpbackup*
