# .github/workflows/build_and_package.yml
name: Build and package DEB

on:
  push:
    branches: ['master']
    tags: ['**']
  pull_request:
    branches: ['**']

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os_version:
          - '22.04'
          - '24.04'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ci/Dockerfile.ubuntu
          push: false
          tags: gpbackup-s3-plugin:${{ matrix.os_version }}
          build-args: OS_VERSION=${{ matrix.os_version }}

      - name: Extract artifacts
        run: |
          mkdir artifacts
          docker create --name temp-container gpbackup-s3-plugin:${{ matrix.os_version }}
          docker cp temp-container:/home/gpadmin/deb-packages artifacts/
          docker cp temp-container:/home/gpadmin/bin artifacts/
          docker rm temp-container

      - name: Upload deb packages
        uses: actions/upload-artifact@v7
        with:
          name: gpbackup-s3-plugin-deb-ubuntu${{ matrix.os_version }}
          path: artifacts/deb-packages/

      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          name: gpbackup-s3-plugin-bin-ubuntu${{ matrix.os_version }}
          path: artifacts/bin/

      - name: Test deb package installation
        uses: greengagedb/greengage-ci/.github/actions/tests/install/deb@v44
        with:
          test_docker: 'ubuntu:${{ matrix.os_version }}'
          artifact_name: 'gpbackup-s3-plugin-deb-ubuntu${{ matrix.os_version }}'
          add_greengage_repo: true
          greengage_repo_url: "https://storage.yandexcloud.net/greengage-repo"
          verify_commands: dpkg -l gpbackup*
